# Generated by Django 2.1.13 on 2020-10-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Parrot', 'Parrot'), ('Unknown', 'Unknown')], default='Unknown', max_length=6)),
                ('name', models.CharField(max_length=6)),
                ('age', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='petstagram.Pet'),
        ),
    ]
