# Generated by Django 2.1.13 on 2020-10-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
