# Generated by Django 2.1.13 on 2021-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0002_auto_20210126_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='default', editable=False),
            preserve_default=False,
        ),
    ]
