# Generated by Django 2.2.28 on 2022-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0004_auto_20220601_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
