# Generated by Django 2.2.28 on 2022-06-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0005_auto_20220601_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, default='asd', max_length=6),
            preserve_default=False,
        ),
    ]
