# Generated by Django 2.2.28 on 2022-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0006_auto_20220601_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
