# Generated by Django 2.2.28 on 2022-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0007_auto_20220601_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(),
        ),
    ]
