# Generated by Django 2.2.28 on 2022-06-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0008_auto_20220601_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='aa',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stana', to='petstagram.Pet'),
            preserve_default=False,
        ),
    ]
