# Generated by Django 2.1.13 on 2020-06-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='base',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='base',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
    ]
