# Generated by Django 2.1.13 on 2020-08-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
