# Generated by Django 2.1.13 on 2020-10-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ImageAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('animals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_polymorphic.Animals')),
                ('name', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_polymorphic.animals',),
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('animals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_polymorphic.Animals')),
                ('name', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_polymorphic.animals',),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_polymorphic.Animals')),
                ('name', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_polymorphic.animals',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_polymorphic.Animals')),
                ('name', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_polymorphic.animals',),
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('animals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_polymorphic.Animals')),
                ('name', models.CharField(max_length=30)),
                ('abilities', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_polymorphic.animals',),
        ),
        migrations.AddField(
            model_name='imageanimals',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_polymorphic.Animals'),
        ),
        migrations.AddField(
            model_name='animals',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_polymorphic.animals_set+', to='contenttypes.ContentType'),
        ),
    ]
