# Generated by Django 2.1.13 on 2020-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Име')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('eng', models.CharField(max_length=10, verbose_name='ЕГН')),
                ('phone', models.CharField(max_length=10, verbose_name='Мобилен телефон')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
            ],
        ),
    ]
