# Generated by Django 2.1.13 on 2020-02-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('rank', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
