# Generated by Django 2.1.13 on 2020-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=512)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
