# Generated by Django 2.1.13 on 2020-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTricks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Име')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('eng', models.CharField(blank=True, max_length=10, null=True, verbose_name='ЕГН')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Мобилен телефон')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('birthday', models.DateTimeField()),
                ('color_code', models.CharField(blank=True, max_length=6, null=True)),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=9)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
