# Generated by Django 2.1.13 on 2020-10-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tricks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admintricks',
            options={'verbose_name': 'Admin Trick', 'verbose_name_plural': 'Admin Tricks'},
        ),
    ]
