# Generated by Django 2.1.13 on 2020-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
