# Generated by Django 2.1.13 on 2020-08-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('course', models.DecimalField(decimal_places=5, max_digits=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
