# Generated by Django 2.1.13 on 2020-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='course',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
