# Generated by Django 2.1.13 on 2020-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20200810_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='course',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
