# Generated by Django 2.1.13 on 2020-10-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20200812_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
