# Generated by Django 2.1.13 on 2020-08-27 07:37

import django.core.validators
from django.db import migrations, models
import template_project.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.IntegerField(validators=[template_project.utils.validators.validate_even])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Въведения мобилен телефоне невалиден', regex='^[0-9]{10,254}$')], verbose_name='Телефон')),
            ],
        ),
    ]
