# Generated by Django 2.1.13 on 2021-08-17 11:41

from django.db import migrations, models
import template_project.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatormodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='confirm_password',
            field=models.CharField(default='', max_length=254, verbose_name='Confirm_password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='description',
            field=models.TextField(default='', verbose_name='Descriptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='egn',
            field=models.CharField(default='', max_length=10, verbose_name='EGN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='name',
            field=models.CharField(default='', max_length=254, verbose_name='First and last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='password',
            field=models.CharField(default='', max_length=254, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatormodel',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validatormodel',
            name='even_field',
            field=models.IntegerField(blank=True, null=True, validators=[template_project.utils.validators.validate_even]),
        ),
    ]
