# Generated by Django 2.1.13 on 2019-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
