# Generated by Django 2.1.13 on 2020-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_files', '0002_auto_20191128_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg', models.ImageField(upload_to='images')),
            ],
        ),
    ]
